/**
 * `<eps-patient-summary>` — the mapped European Patient Summary.
 *
 * The last step of the save pipeline: the composition was committed, openFHIR
 * mapped it to a FHIR document Bundle, that Bundle was stored, and this view
 * renders it.
 *
 * It re-reads the Bundle by id rather than being handed one. That is what makes
 * the URL sufficient on its own — reload, deep link and back button all work,
 * with no store to keep in sync. The cost is one fetch on entry, which is the
 * cheaper half of the trade.
 *
 * The view is anchored to the EPS PROFILE, not to the Bundle: `fhir/eps-model`
 * supplies all 17 sections and the per-resource element lists, `fhir/eps-view`
 * lays the document over them. A section the mapping never emitted is shown as
 * "not present" rather than being absent from the page, because that is a fact
 * about the document the reader needs and it is invisible in a view that only
 * renders what it was given. No conformance verdict is rendered either way.
 *
 * LIGHT DOM like every view here (`createRenderRoot` returns `this`), so there
 * is no `static styles` — CSS lives in `styles/views.css` under this tag name.
 */

import { LitElement, html, nothing, type PropertyValues, type TemplateResult } from 'lit';
import { customElement, property, state } from 'lit/decorators.js';

import { readBundle, type FhirBundle, type FhirResource } from '../fhir/bundle';
import {
  epsDocumentView,
  type Datapoint,
  type EpsDocumentView,
  type EpsSectionView,
  type ResourceView,
} from '../fhir/eps-view';
import { findComposition, orDash } from '../fhir/ips';
import type { PatientView } from '../fhir/patient';
import { navigate } from '../shell';

@customElement('eps-patient-summary')
export class EpsPatientSummary extends LitElement {
  /** Light DOM — see the class comment. */
  createRenderRoot() {
    return this;
  }

  @property({ attribute: false }) patientId = '';
  @property({ attribute: false }) patient?: PatientView;
  /** The composition this summary was mapped from — the way back. */
  @property({ attribute: false }) uid = '';
  @property({ attribute: false }) templateId = '';
  @property({ attribute: false }) bundleId = '';

  @state() private bundle?: FhirBundle;
  @state() private loading = false;
  @state() private error = '';
  @state() private showRaw = false;

  /**
   * Which raw cells are open, keyed by resource+path.
   *
   * A Set rather than a flag per Datapoint because the datapoints are rebuilt
   * from the Bundle on every render — state stored on them would be discarded
   * the moment anything else changed.
   */
  @state() private openRaw = new Set<string>();
  /**
   * Expand-all/collapse-all. `undefined` leaves each section on its own
   * default (open when present), which is the state the page loads in.
   */
  @state() private forceOpen?: boolean;

  updated(changed: PropertyValues): void {
    // Re-read only when the id actually changes. The shell re-renders this view
    // on every route change, and refetching on each one would flash the loading
    // state over a Bundle already on screen.
    if (changed.has('bundleId')) void this.load();
  }

  private async load(): Promise<void> {
    this.bundle = undefined;
    this.error = '';

    if (!this.bundleId) {
      this.error = 'No Bundle was named in the URL, so there is nothing to show.';
      return;
    }

    this.loading = true;
    try {
      this.bundle = await readBundle(this.bundleId);
    } catch (err) {
      this.error = (err as Error).message;
    } finally {
      this.loading = false;
    }
  }

  /** Back to the composition this was mapped from. */
  private toComposition(): void {
    navigate(
      `#/patients/${encodeURIComponent(this.patientId)}/compositions/${encodeURIComponent(this.uid)}` +
        (this.templateId ? `?template=${encodeURIComponent(this.templateId)}` : ''),
    );
  }

  private toggleRaw(key: string): void {
    const next = new Set(this.openRaw);
    if (next.has(key)) next.delete(key);
    else next.add(key);
    this.openRaw = next;
  }

  render() {
    return html`
      <div class="summary-head">
        <div>
          <h2>European Patient Summary</h2>
          <p>
            Generated by openFHIR from the saved composition
            ${this.bundleId
              ? html`· <span class="mono">Bundle/${this.bundleId}</span>`
              : nothing}
          </p>
        </div>
        <div class="spacer"></div>
        ${this.bundle
          ? html`
              <button
                class="btn"
                @click=${() => (this.forceOpen = true)}
                data-testid="eps-expand-all"
              >
                Expand all
              </button>
              <button
                class="btn"
                @click=${() => (this.forceOpen = false)}
                data-testid="eps-collapse-all"
              >
                Collapse all
              </button>
            `
          : nothing}
        <button class="btn" @click=${this.toComposition} data-testid="summary-back">
          Back to composition
        </button>
      </div>

      ${this.renderBody()}
    `;
  }

  private renderBody() {
    if (this.loading) {
      return html`<div class="summary-state" data-testid="summary-loading">
        <span class="spinner"></span> Loading the Patient Summary…
      </div>`;
    }

    if (this.error) {
      // The Bundle is gone or was never stored. The composition itself is
      // unaffected, so the way out is back to the record rather than a retry.
      return html`
        <div class="summary-state error" data-testid="summary-error">
          <p>Could not load the Patient Summary.</p>
          <p class="mono">${this.error}</p>
          <button class="btn" @click=${this.toComposition}>Back to the composition</button>
        </div>
      `;
    }

    if (!this.bundle) return nothing;

    if (!findComposition(this.bundle)) {
      // A Bundle with no Composition is not a document: there is no section
      // order to render, and inventing one by grouping entries would present a
      // structure the source never asserted.
      return html`
        <div class="summary-state error" data-testid="summary-no-composition">
          <p>This Bundle contains no Composition, so it cannot be shown as a patient summary.</p>
          <p>It holds ${this.bundle.entry?.length ?? 0} resources.</p>
          ${this.renderRawToggle()}
        </div>
      `;
    }

    const view = epsDocumentView(this.bundle);

    return html`
      ${this.renderBanner(view)}
      ${view.sections.map((section) => this.renderSection(section))}
      ${this.renderOrphans(view.orphans)}
      ${this.renderRawToggle()}
    `;
  }

  /**
   * The patient banner, plus the document's own header.
   *
   * The demographics read the Bundle's Patient entry when it has one and
   * otherwise fall back to the patient in route context. openFHIR's output
   * carries no Patient resource today — the composition it maps from has no
   * demographics — so the fallback is the normal path here, not an edge case.
   *
   * The Composition and Bundle metadata beside it identify WHICH document this
   * is: `identifier` and `timestamp` name this exact instance, and neither was
   * on screen before.
   */
  private renderBanner(view: EpsDocumentView) {
    const patientResource = this.bundle?.entry?.find(
      (e) => e.resource?.resourceType === 'Patient',
    )?.resource;

    const name = patientResource
      ? formatHumanName(patientResource)
      : (this.patient?.name ?? 'Unknown patient');
    const birthDate = (patientResource?.birthDate as string) ?? this.patient?.birthDate;
    const identifier =
      (patientResource?.identifier as { value?: string }[])?.[0]?.value ??
      this.patient?.identifier;

    const composition = view.composition;
    const cell = (view: ResourceView | undefined, path: string) =>
      view?.datapoints.find((datapoint) => datapoint.path === path);

    return html`
      <div class="summary-banner" data-testid="summary-banner">
        <div>
          <div class="label">Patient</div>
          <div class="value" data-testid="summary-patient-name">${name}</div>
        </div>
        <div>
          <div class="label">Date of birth</div>
          <div class="value">${orDash(birthDate)}</div>
        </div>
        <div>
          <div class="label">Identifier</div>
          <div class="value mono">${orDash(identifier)}</div>
        </div>
        <div>
          <div class="label">Document</div>
          <div class="value">${orDash(cell(composition, 'title')?.text)}</div>
        </div>
        <div>
          <div class="label">Date</div>
          <div class="value">${orDash(cell(composition, 'date')?.text)}</div>
        </div>
        <div>
          <div class="label">Status</div>
          <div class="value">${orDash(cell(composition, 'status')?.text)}</div>
        </div>
        <div>
          <div class="label">Type</div>
          <div class="value">
            ${orDash(cell(composition, 'type')?.text)}
            ${this.renderCodings(cell(composition, 'type')?.codings ?? [])}
          </div>
        </div>
        <div>
          <div class="label">Composition identifier</div>
          <div class="value mono">${orDash(cell(composition, 'identifier')?.text)}</div>
        </div>
        <div>
          <div class="label">Author</div>
          <div class="value">${orDash(cell(composition, 'author')?.text)}</div>
        </div>
        ${view.bundleMeta
          .filter((datapoint) => datapoint.present)
          .map(
            (datapoint) => html`
              <div>
                <div class="label">Bundle ${datapoint.label.toLowerCase()}</div>
                <div class="value mono">${datapoint.text}</div>
              </div>
            `,
          )}
        ${patientResource
          ? nothing
          : html`<p class="banner-note">
              Demographics from the patient record — the mapped Bundle carries no Patient resource.
            </p>`}
      </div>
    `;
  }

  /**
   * One profile section.
   *
   * Rendered whether or not the document carries it. An absent section is
   * stated neutrally as "not present" — no warning styling and no conformance
   * badge, even for a section the profile marks mandatory, because this viewer
   * reports what the document says rather than grading it.
   */
  private renderSection(section: EpsSectionView) {
    const slice = section.spec?.slice ?? slugOf(section.title);
    const open = this.forceOpen ?? section.present;

    return html`
      <details
        class="eps-section ${section.present ? '' : 'absent'}"
        ?open=${open}
        data-testid="eps-section-${slice}"
      >
        <summary>
          <span class="eps-section-title">${section.title}</span>
          ${section.code
            ? html`<span class="eps-section-code mono">http://loinc.org|${section.code}</span>`
            : nothing}
          ${section.spec ? nothing : html`<span class="eps-section-extra">not in profile</span>`}
        </summary>

        ${section.present
          ? html`
              ${section.resources.length
                ? section.resources.map((resource) => this.renderResource(resource, slice))
                : html`<p class="eps-section-note">
                    This section is present but lists no entries.
                  </p>`}
              ${section.emptyReason
                ? html`<p class="eps-section-note">
                    Empty reason: ${section.emptyReason}
                  </p>`
                : nothing}
              ${section.unresolved.length
                ? html`<ul class="section-unresolved">
                    ${section.unresolved.map(
                      (display) =>
                        html`<li>
                          ${display} <span class="hint">(not included in this Bundle)</span>
                        </li>`,
                    )}
                  </ul>`
                : nothing}
            `
          : html`<p class="eps-section-note">Not present in this document.</p>`}
      </details>
    `;
  }

  /**
   * One resource as a definition list of every datapoint the model knows.
   *
   * A list rather than a table row: the previous table showed 4–6 chosen
   * columns per type and dropped the rest, which is the loss this view exists
   * to undo. Rows read down instead of across, so adding a field costs nothing
   * horizontally.
   */
  private renderResource(resource: ResourceView, scope: string): TemplateResult {
    const present = resource.datapoints.filter((datapoint) => datapoint.present);
    const absent = resource.datapoints.filter((datapoint) => !datapoint.present);

    return html`
      <article class="eps-resource" data-testid="eps-resource-${resource.resourceType}">
        <header>
          <span class="eps-resource-type">${resource.resourceType}</span>
          <span class="eps-resource-title">${resource.title}</span>
        </header>

        <dl class="eps-dl">
          ${present.map((datapoint) => this.renderDatapoint(datapoint, `${scope}/${resource.resourceType}`))}
          ${absent.map((datapoint) => this.renderDatapoint(datapoint, `${scope}/${resource.resourceType}`))}
        </dl>

        ${resource.residual.length
          ? html`
              <div class="eps-residual">
                <div class="eps-residual-head">Other fields present</div>
                <dl class="eps-dl">
                  ${resource.residual.map((datapoint) =>
                    this.renderDatapoint(datapoint, `${scope}/${resource.resourceType}`),
                  )}
                </dl>
              </div>
            `
          : nothing}
      </article>
    `;
  }

  /** One label/value row, with its codings, nested groups and raw toggle. */
  private renderDatapoint(datapoint: Datapoint, scope: string): TemplateResult {
    const key = `${scope}/${datapoint.path}`;
    const rawOpen = this.openRaw.has(key);

    return html`
      <div
        class="eps-dp ${datapoint.present ? '' : 'absent'}"
        data-testid="eps-datapoint-${datapoint.path}"
      >
        <dt>${datapoint.label} <span class="eps-dp-path mono">${datapoint.path}</span></dt>
        <dd>
          <span class="eps-dp-value">${orDash(datapoint.text)}</span>
          ${this.renderCodings(datapoint.codings)}
          ${datapoint.reference && !datapoint.reference.resolved && datapoint.present
            ? html`<span class="hint">(not included in this Bundle)</span>`
            : nothing}
          ${datapoint.present
            ? html`
                <button
                  class="eps-raw-toggle"
                  @click=${() => this.toggleRaw(key)}
                  data-testid="eps-raw-toggle-${datapoint.path}"
                >
                  ${rawOpen ? 'Hide' : 'Raw'}
                </button>
              `
            : nothing}
          ${rawOpen
            ? html`<pre class="eps-raw">${JSON.stringify(datapoint.raw, null, 2)}</pre>`
            : nothing}
          ${datapoint.groups?.length
            ? html`
                <div class="eps-groups">
                  ${datapoint.groups.map(
                    (group) => html`
                      <div class="eps-group">
                        <div class="eps-group-head">${group.label}</div>
                        <dl class="eps-dl">
                          ${group.datapoints
                            .filter((child) => child.present)
                            .map((child) => this.renderDatapoint(child, `${key}`))}
                        </dl>
                      </div>
                    `,
                  )}
                </div>
              `
            : nothing}
          ${datapoint.reference?.view
            ? html`
                <div class="eps-groups">
                  ${this.renderResource(datapoint.reference.view, key)}
                </div>
              `
            : nothing}
        </dd>
      </div>
    `;
  }

  /**
   * Every coding as a `system|code` chip.
   *
   * All of them, not `coding[0]`: the fixture's `Condition.clinicalStatus`
   * carries four and the previous view rendered one, with no sign that three
   * more existed.
   */
  private renderCodings(codings: Datapoint['codings']) {
    if (!codings.length) return nothing;

    return html`
      <span class="eps-codings">
        ${codings.map(
          (coding) => html`
            <span class="eps-coding mono" title=${coding.display ?? ''}>
              ${coding.system ?? ''}${coding.system && coding.code ? '|' : ''}${coding.code ?? ''}
            </span>
          `,
        )}
      </span>
    `;
  }

  /**
   * Resources no section reached.
   *
   * A Bundle entry that nothing references is still part of the document. The
   * previous view could not show one at all, which is how three Devices sat in
   * the fixture entirely off-screen.
   */
  private renderOrphans(orphans: ResourceView[]) {
    if (!orphans.length) return nothing;

    return html`
      <details class="eps-section eps-orphans" open data-testid="eps-orphans">
        <summary>
          <span class="eps-section-title">Resources not referenced by any section</span>
          <span class="eps-section-code mono">${orphans.length}</span>
        </summary>
        ${orphans.map((resource) => this.renderResource(resource, 'orphans'))}
      </details>
    `;
  }

  /**
   * The raw Bundle, for the demo audience.
   *
   * `section.text.div` narrative is deliberately NOT rendered as HTML anywhere
   * in this view: it is server-supplied XHTML and would need sanitising first.
   * The structured datapoints above carry the same information safely, and this
   * toggle is how anyone who wants the original can still see it.
   */
  private renderRawToggle() {
    return html`
      <div class="summary-raw">
        <button
          class="btn"
          @click=${() => (this.showRaw = !this.showRaw)}
          data-testid="summary-raw-toggle"
        >
          ${this.showRaw ? 'Hide' : 'Show'} raw FHIR Bundle
        </button>
        ${this.showRaw
          ? html`<pre data-testid="summary-raw">${JSON.stringify(this.bundle, null, 2)}</pre>`
          : nothing}
      </div>
    `;
  }
}

/** `given family`, falling back to `text` — the parts an IPS banner shows. */
function formatHumanName(patient: FhirResource): string {
  const name = (patient.name as { text?: string; given?: string[]; family?: string }[])?.[0];
  if (!name) return 'Unknown patient';
  if (name.text) return name.text;

  return [name.given?.join(' '), name.family].filter(Boolean).join(' ') || 'Unknown patient';
}

/** A testid-safe slug, for a document section the profile does not describe. */
function slugOf(title: string): string {
  return title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'section';
}

declare global {
  interface HTMLElementTagNameMap {
    'eps-patient-summary': EpsPatientSummary;
  }
}
