/**
 * FHIR client. Talks only to the BFF — never to HAPI directly — so the SPA
 * stays same-origin and no CORS is needed.
 */

import {
  patientsFromBundle,
  toPatientView,
  draftToFhirPatient,
  type FhirPatient,
  type PatientDraft,
  type PatientView,
} from './patient';

async function json<T>(res: Response, context: string): Promise<T> {
  const text = await res.text();
  if (!res.ok) {
    throw new Error(`${context} failed (HTTP ${res.status}): ${text.slice(0, 1000)}`);
  }
  return text ? (JSON.parse(text) as T) : ({} as T);
}

/** Patient search. An empty `name` lists the first page. */
export async function searchPatients(name = ''): Promise<PatientView[]> {
  const query = name.trim() ? `?name=${encodeURIComponent(name.trim())}` : '';
  const bundle = await json<any>(await fetch(`/api/patients${query}`), 'patient search');
  return patientsFromBundle(bundle).map((p) => toPatientView(p));
}

export async function getPatient(id: string): Promise<PatientView> {
  const patient = await json<FhirPatient>(
    await fetch(`/api/patients/${encodeURIComponent(id)}`),
    'patient read',
  );
  return toPatientView(patient);
}

export interface CreatedPatient {
  patientId: string;
  /** Auto-generated by EHRbase and linked to the patient — never chosen here. */
  ehrId: string | null;
}

/**
 * Creates a patient and their openEHR record.
 *
 * One call, because the two must not drift apart: the BFF creates the FHIR
 * Patient, then the EHR carrying that patient's id as its subject reference.
 * The EHR id is generated by EHRbase, so nothing client-side invents one.
 */
export async function createPatient(draft: PatientDraft): Promise<CreatedPatient> {
  return json<CreatedPatient>(
    await fetch('/api/patients', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(draftToFhirPatient(draft)),
    }),
    'patient creation',
  );
}

/**
 * The EHR id for a patient, or null when they have none yet.
 *
 * A 404 here is a legitimate answer, not a failure: it means this patient has
 * no EHR, which the Compositions view handles by offering to create one.
 */
export async function getPatientEhr(id: string): Promise<string | null> {
  const res = await fetch(`/api/patients/${encodeURIComponent(id)}/ehr`);
  if (res.status === 404) return null;
  const body = await json<{ ehrId: string | null }>(res, 'EHR lookup');
  return body.ehrId ?? null;
}
