/**
 * FHIR client. Talks only to the BFF — never to HAPI directly — so the SPA
 * stays same-origin and no CORS is needed.
 */

import {
  patientsFromBundle,
  toPatientView,
  draftToFhirPatient,
  type FhirPatient,
  type PatientDraft,
  type PatientView,
} from './patient';

async function json<T>(res: Response, context: string): Promise<T> {
  const text = await res.text();
  if (!res.ok) {
    throw new Error(`${context} failed (HTTP ${res.status}): ${text.slice(0, 1000)}`);
  }
  return text ? (JSON.parse(text) as T) : ({} as T);
}

/** Patient search. An empty `name` lists the first page. */
export async function searchPatients(name = ''): Promise<PatientView[]> {
  const query = name.trim() ? `?name=${encodeURIComponent(name.trim())}` : '';
  const bundle = await json<any>(await fetch(`/api/patients${query}`), 'patient search');
  return patientsFromBundle(bundle).map((p) => toPatientView(p));
}

export async function getPatient(id: string): Promise<PatientView> {
  const patient = await json<FhirPatient>(
    await fetch(`/api/patients/${encodeURIComponent(id)}`),
    'patient read',
  );
  return toPatientView(patient);
}

export interface CreatedPatient {
  patientId: string;
  /** Auto-generated by EHRbase and linked to the patient — never chosen here. */
  ehrId: string | null;
}

/**
 * Creates a patient and their openEHR record.
 *
 * One call, because the two must not drift apart: the BFF creates the FHIR
 * Patient, then the EHR carrying that patient's id as its subject reference.
 * The EHR id is generated by EHRbase, so nothing client-side invents one.
 */
export async function createPatient(draft: PatientDraft): Promise<CreatedPatient> {
  return json<CreatedPatient>(
    await fetch('/api/patients', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(draftToFhirPatient(draft)),
    }),
    'patient creation',
  );
}

/**
 * The EHR id for a patient, or null when they have none yet.
 *
 * A 404 here is a legitimate answer, not a failure: it means this patient has
 * no EHR, which the Compositions view handles by offering to create one.
 */
export async function getPatientEhr(id: string): Promise<string | null> {
  const res = await fetch(`/api/patients/${encodeURIComponent(id)}/ehr`);
  if (res.status === 404) return null;
  const body = await json<{ ehrId: string | null }>(res, 'EHR lookup');
  return body.ehrId ?? null;
}

/** One thing the delete could not remove, named so the report can say which. */
export interface DeleteFailure {
  uid?: string;
  id?: string;
  status: number;
  detail?: string;
}

/**
 * What a patient deletion actually did.
 *
 * A report rather than a boolean, because the delete spans two servers with no
 * transaction between them: a run that removed the compositions but not the
 * Bundles is a real outcome that has to be describable. `found` and `deleted`
 * are counted separately so a partial run is visible rather than rounded off.
 */
export interface DeleteResult {
  patientId: string;
  ehrId: string | null;
  compositions: { found: number; deleted: number; failed: DeleteFailure[] };
  bundles: { found: number; deleted: number; failed: DeleteFailure[] };
  patient: { deleted: boolean };
}

/** What deleting a patient would remove, for the confirmation dialog. */
export interface DeletionPreview {
  patientId: string;
  ehrId: string | null;
  compositions: number;
  bundles: number;
}

export async function getDeletionPreview(id: string): Promise<DeletionPreview> {
  return json<DeletionPreview>(
    await fetch(`/api/patients/${encodeURIComponent(id)}/deletion-preview`),
    'deletion preview',
  );
}

/**
 * Deletes a patient, their openEHR compositions and their stored FHIR Bundles.
 *
 * Note what does NOT happen: the openEHR EHR shell survives. This CDR answers
 * 405 to `DELETE /ehr/{id}` and its admin API is 403 with the BFF's
 * credentials, so an empty EHR is left behind. Composition deletion is also
 * logical — the CDR retains version history. Neither is worth surfacing in the
 * UI, but both are why this is not the clean erasure the wording implies.
 *
 * A 200 can still carry failures: see `DeleteResult`. Callers that care should
 * read `failed[]` rather than treating a resolved promise as total success.
 */
export async function deletePatient(id: string): Promise<DeleteResult> {
  return json<DeleteResult>(
    await fetch(`/api/patients/${encodeURIComponent(id)}`, { method: 'DELETE' }),
    'patient deletion',
  );
}
